export enum AgtkPluginUiParameterType {
  String = 'String',
  MultiLineString = 'MultiLineString',
  Number = 'Number',
  Json = 'Json',
  ImageId = 'ImageId',
  TextId = 'TextId',
  SceneId = 'SceneId',
  TilesetId = 'TilesetId',
  AnimationId = 'AnimationId',
  ObjectId = 'ObjectId',
  FontId = 'FontId',
  MovieId = 'MovieId',
  BgmId = 'BgmId',
  SeId = 'SeId',
  VoiceId = 'VoiceId',
  VariableId = 'VariableId',
  SwitchId = 'SwitchId',
  AnimOnlyId = 'AnimOnlyId',
  PortalId = 'PortalId',
  CustomId = 'CustomId',
  Embedded = 'Embedded',
  EmbeddedEditable = 'EmbeddedEditable',
  SwitchVariableObjectId = 'SwitchVariableObjectId',
  DatabaseId = 'DatabaseId'
}
